version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mini_crm_db
    restart: always
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mini_crm
      MYSQL_USER: mini_crm
      MYSQL_PASSWORD: secret123
    volumes:
      - mini_crm_db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mini_crm_laravel_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "${API_PORT:-8000}:8000"
    command: >
      sh -c "composer install && php artisan migrate && php artisan serve --host=0.0.0.0"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mini_crm_vue_app
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    command: npm run dev

volumes:
  mini_crm_db_data:
